# Generated by Django 5.2.6 on 2026-02-12 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postlikes',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postviews',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together={('post', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='postviews',
            unique_together={('post', 'owner')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['owner', '-created_at'], name='posts_post_owner_i_577587_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_active', '-created_at'], name='posts_post_is_acti_3afc54_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post', '-created_at'], name='posts_postc_post_id_3d25fd_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['owner', '-created_at'], name='posts_postc_owner_i_e36483_idx'),
        ),
        migrations.AddIndex(
            model_name='postlikes',
            index=models.Index(fields=['post', 'owner'], name='posts_postl_post_id_421930_idx'),
        ),
        migrations.AddIndex(
            model_name='postlikes',
            index=models.Index(fields=['post', '-created_at'], name='posts_postl_post_id_f26482_idx'),
        ),
        migrations.AddIndex(
            model_name='postviews',
            index=models.Index(fields=['post', 'owner'], name='posts_postv_post_id_cd0db8_idx'),
        ),
    ]
