# Generated by Django 5.2.4 on 2025-09-24 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='file',
            name='height',
        ),
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.RemoveField(
            model_name='file',
            name='width',
        ),
        migrations.AddField(
            model_name='file',
            name='is_temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message'),
        ),
    ]
