# Generated by Django 5.2.4 on 2025-09-02 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messageaction',
            unique_together={('message', 'user', 'value')},
        ),
        migrations.RemoveField(
            model_name='messageaction',
            name='action_type',
        ),
    ]
