# Generated by Django 5.2.6 on 2025-09-09 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=10)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='room_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grouproommember',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='group_room',
        ),
        migrations.AlterUniqueTogether(
            name='grouproommember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='grouproommember',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='privateroom',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='privateroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='privateroom',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='private_room',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('owner', 'Owner')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_members', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='rooms', through='chat.RoomMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupRoom',
        ),
        migrations.DeleteModel(
            name='GroupRoomMember',
        ),
        migrations.DeleteModel(
            name='PrivateRoom',
        ),
    ]
