# Generated by Django 5.2.4 on 2025-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_file_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
