# Generated by Django 5.2.4 on 2025-09-25 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_file_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.AddField(
            model_name='file',
            name='owners',
            field=models.ManyToManyField(related_name='files', to=settings.AUTH_USER_MODEL),
        ),
    ]
