# Generated by Django 5.2.4 on 2025-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_file_owner_file_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='message',
        ),
        migrations.AddField(
            model_name='file',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='chat.message'),
        ),
    ]
