# Generated by Django 5.2.6 on 2026-02-04 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_file_message_file_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_temporary', 'uploaded_at'], name='chat_file_is_temp_6acf1c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='chat_messag_created_f18bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at'], name='chat_messag_room_id_edc775_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='chat_messag_sender__62c9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'is_delivered'], name='chat_messag_user_id_bc8cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'is_read'], name='chat_messag_user_id_7c6d14_idx'),
        ),
    ]
