# Generated by Django 5.2.6 on 2026-02-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_file_chat_file_is_temp_6acf1c_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='messageaction',
            options={'ordering': ['-created_at']},
        ),
    ]
