# Generated by Django 5.2.4 on 2025-08-09 07:49

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='marked',
            field=models.ManyToManyField(blank=True, null=True, related_name='marked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_id',
            field=models.CharField(default=uuid.UUID('cf48c70f-4f65-48ad-9d0e-1bf825063053'), max_length=128),
        ),
    ]
