# Generated by Django 5.2.4 on 2025-09-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
