# Generated by Django 5.2.4 on 2025-08-09 11:17

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_marked_alter_story_story_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='marked',
            field=models.ManyToManyField(blank=True, related_name='marked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_id',
            field=models.CharField(default=uuid.UUID('bc0aeb0e-a765-4cdb-8a79-411ea5d87d8c'), max_length=128),
        ),
    ]
