# Generated by Django 5.2.4 on 2025-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_private',
        ),
        migrations.AddField(
            model_name='story',
            name='audience',
            field=models.CharField(choices=[('pubic', 'Public'), ('contact', 'Contacts'), ('marked', 'Marked')], default='pubic', max_length=10),
        ),
    ]
