# Generated by Django 5.2.4 on 2025-08-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_is_private_alter_story_marked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_id',
        ),
    ]
