# Generated by Django 5.2.6 on 2025-10-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_story_is_private_story_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audience',
            field=models.CharField(choices=[('public', 'Public'), ('contact', 'Contacts'), ('marked', 'Marked')], default='public', max_length=10),
        ),
    ]
