# Generated by Django 5.2.6 on 2026-02-12 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storyreaction',
            options={'ordering': ['-reacted_at']},
        ),
        migrations.AlterModelOptions(
            name='storyviewed',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterUniqueTogether(
            name='storyviewed',
            unique_together={('story', 'viewer')},
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['is_active', '-created_at'], name='stories_sto_is_acti_88a762_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['owner', 'is_active', '-created_at'], name='stories_sto_owner_i_da535d_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['audience', 'is_active'], name='stories_sto_audienc_64864a_idx'),
        ),
        migrations.AddIndex(
            model_name='storyreaction',
            index=models.Index(fields=['story', '-reacted_at'], name='stories_sto_story_i_8d5a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='storyviewed',
            index=models.Index(fields=['story', 'viewer'], name='stories_sto_story_i_3eb1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='storyviewed',
            index=models.Index(fields=['viewer', '-viewed_at'], name='stories_sto_viewer__ebc411_idx'),
        ),
    ]
