# Generated by Django 5.2.4 on 2025-08-12 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_remove_story_story_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryViwed',
            new_name='StoryViewed',
        ),
    ]
