# Generated by Django 5.2.4 on 2025-08-04 13:15

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_username_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[accounts.validators.validate_username]),
        ),
    ]
