# Generated by Django 5.2.6 on 2026-02-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_premiumusername'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('owner', 'contact')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', 'contact'], name='accounts_co_owner_i_ef8186_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='accounts_cu_usernam_ab560e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', '-date_joined'], name='accounts_cu_is_acti_eecdbc_idx'),
        ),
    ]
